services:
  broker:
    build:
      context: .
      dockerfile: src/integration-service/Broker/Dockerfile
    environment:
      BROKER_BIND_IP: "0.0.0.0"
      BROKER_BIND_PORT: "6001"
      BROKER_DB_PATH: "/app/data/broker.db"
    ports:
      - "6001:6001"
    volumes:
      - broker-data:/app/data

  receiver:
    build:
      context: .
      dockerfile: src/consumers/receivers/Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - broker
    environment:
    - RECEIVER_EFFECTS_PATH=/data/effects.log
    volumes:
    - receiver-data:/data
  sender:
    build:
      context: .
      dockerfile: src/providers/providers/Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - broker
volumes:
  broker-data:
  receiver-data:  